### ISSUE TITLE
Update emitter parameters on the fly?

### ISSUE THREAD

**Issue by samyH** [fazeaction/three-gpu-particle-system#10]
Hi,

I was wondering if there is a way to change the the emitter parameters?

I'm trying to TWEEN the startSize parameter in particular 
`const num = {x: 11}
    var tween = new TWEEN.Tween(num)
    .to({x: 0}, 2000)
    .onUpdate(function () {
      emitter.setParameters({startSize:num})
    })
    .start();`
Thanks in advance

**Comment by fazeaction** [comment]
Sorry to reply to you so late. I think is not possible because all the animation is happening directly in the GPU and once the buffers are set up and uploaded to the GPU the animation is time-based.  However, I think the animation that you are trying to do is possible just using startSize and endSize. Please, check the shader and you will have a better idea of what is happening behind scenes. (https://github.com/fazeaction/three-gpu-particle-system/blob/master/src/shaders/particles-billboard-instanced_vs.glsl). Also I highly recommended checking the original file with helpful comments (https://github.com/greggman/tdl/blob/master/tdl/particles.js)
